configfile: 'src/setup/config.yml'

########################
### GENERATION RULES ###
########################

rule default:
    input:
        'data/annotation/GRCh37',
        'data/annotation/GRCh38',

rule annotation_GRCh37:
    input:
        'data/annotation/GRCh37',
        'data/vep/GRCh37'

rule annotation_GRCh38:
    input:
        'data/annotation/GRCh38',
        'data/vep/GRCh38'

rule prescored_GRCh37:
    input:
        'data/prescored/GRCh37/whole_genome_SNVs.tsv.gz',
        'data/prescored/GRCh37/whole_genome_SNVs.tsv.gz.tbi'

rule prescored_GRCh38:
    input:
        'data/prescored/GRCh38/whole_genome_SNVs.tsv.gz' ,
        'data/prescored/GRCh38/whole_genome_SNVs.tsv.gz.tbi'

######################
### WORKFLOW RULES ###
######################

rule unpack_annotation:
    input:
        'data/Annotation{GenomeBuild}.tar.gz'
    output:
        'data/annotation/GRCh{GenomeBuild}'
    shell:
        '''
        tar -zxf {input} -C {output}
        '''

rule download_annotation37:
    output:
        temp('data/Annotation37.tar.gz')
    shell:
        '''
        wget -c -o {output} {config[AnnotationDB37]}
        wget -o {output}.md5 {config[AnnotationDB37]}.md5
        md5sum -c {output}.md5
        '''

rule download_annotation38:
    output:
        temp('data/Annotation38.tar.gz')
    shell:
        '''
        wget -c -o {output} {config[AnnotationDB38]}
        wget -o {output}.md5 {config[AnnotationDB38]}.md5
        md5sum -c {output}.md5
        '''

rule download_prescored37:
    output:
        prescore='data/prescored/GRCh37/whole_genome_SNVs.tsv.gz',
        tabix='data/prescored/GRCh37/whole_genome_SNVs.tsv.gz.tbi'
    shell:
        '''
        wget -c -o {output.prescore} {config[PrescoredSNV37]}
        wget -c -o {output.tabix} {config[PrescoredSNV37]}.tbi
        wget -o {output.prescore}.md5 {config[PrescoredSNV37]}.md5
        md5sum -c {output.prescore}.md5
        '''

rule download_prescored38:
    output:
        prescore='data/prescored/GRCh38/whole_genome_SNVs.tsv.gz',
        tabix='data/prescored/GRCh38/whole_genome_SNVs.tsv.gz.tbi'
    shell:
        '''
        wget -c -o {output.prescore} {config[PrescoredSNV38]}
        wget -c -o {output.tabix} {config[PrescoredSNV38]}.tbi
        wget -o {output.prescore}.md5 {config[PrescoredSNV38]}.md5
        md5sum -c {output.prescore}.md5
        '''
