configfile: config.yml

########################
### GENERATION RULES ###
########################

rule all:
    input:

rule annotation_GRCh37:
    '%s/annotation/GRCh37' % (config['DatabasePath']),
    '%s/vep/GRCh37' % config['DatabasePath']

rule annotation_GRCh38:
    '%s/annotation/GRCh38' % (config['DatabasePath']),
    '%s/vep/GRCh38' % config['DatabasePath']


rule prescored_GRCh37:
    input:
        '%s/prescored/GRCh37/whole_genome_SNVs.tsv.gz' % {config['DatabasePath']},
        '%s/prescored/GRCh37/whole_genome_SNVs.tsv.gz.tbi' % {config['DatabasePath']}

rule prescored_GRCh38:
    input:
        '%s/prescored/GRCh38/whole_genome_SNVs.tsv.gz' % {config['DatabasePath']},
        '%s/prescored/GRCh38/whole_genome_SNVs.tsv.gz.tbi' % {config['DatabasePath']}

######################
### WORKFLOW RULES ###
######################

rule setup_vep:
    output:
        '%s/vep/GRCh{GenomeBuilt}' % config['DatabasePath']
    conda:
        '../pipeline/environment.yml'
    shell:
        '''
        vep_install -a cf -s homo_sapiens -y GRhCh{GenomeBuilt} -v 90 -c {config[DatabasePath]}/vep/GRCh{GenomeBuilt} -CONVERT
        '''

rule unpack_annotation:
    input:
        '%s/Annotation{built}.tar.gz' % (config['DatabasePath'])
    output:
        '%s/annotation/GRCh{built}' % (config['DatabasePath'])
    shell:
        '''
        tar -zxf {input} -C {output}
        '''

rule download_annotation37:
    output:
        temp('data/Annotation37.tar.gz')
    shell:
        '''
        wget -c -o {output} {config[AnnotationDB37]}
        wget -o {output}.md5 {config[AnnotationDB37]}.md5
        md5sum -c {output}.md5
        '''

rule download_annotation38:
    output:
        temp('data/Annotation38.tar.gz')
    shell:
        '''
        wget -c -o {output} {config[AnnotationDB38]}
        wget -o {output}.md5 {config[AnnotationDB38]}.md5
        md5sum -c {output}.md5
        '''

rule download_prescored37:
    output:
        prescore='%s/prescored/GRCh37/whole_genome_SNVs.tsv.gz'  % {config[DatabasePath]},
        tabix='%s/prescored/GRCh37/whole_genome_SNVs.tsv.gz.tbi' % {config[DatabasePath]}
    shell:
        '''
        wget -c -o {output.prescore} {config[PrescoredSNV37]}
        wget -c -o {output.tabix} {config[PrescoredSNV37]}.tbi
        wget -o {output.prescore}.md5 {config[PrescoredSNV37]}.md5
        md5sum -c {output.prescore}.md5
        '''

rule download_prescored38:
    output:
        prescore='%s/prescored/GRCh38/whole_genome_SNVs.tsv.gz'  % {config[DatabasePath]},
        tabix='%s/prescored/GRCh38/whole_genome_SNVs.tsv.gz.tbi' % {config[DatabasePath]}
    shell:
        '''
        wget -c -o {output.prescore} {config[PrescoredSNV38]}
        wget -c -o {output.tabix} {config[PrescoredSNV38]}.tbi
        wget -o {output.prescore}.md5 {config[PrescoredSNV38]}.md5
        md5sum -c {output.prescore}.md5
        '''
