---
name: cadd-minimal
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - ensembl-vep=95.1
  - python=2.7
  - scikit-learn=0.20.4
  - htslib=1.9
  - pysam=0.11.2
  - pyvcf=0.6.8
  - pandas
